services:
- type: web
name: recomendaciones-backend
env: node
plan: free
region: oregon
buildCommand: npm install
startCommand: node index.js
rootDir: backend
envVars:
 - key: OPENROUTER_API_KEY
 value: <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>


